# -------- Build Frontend --------
FROM node:20 AS frontend-builder

WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend .
RUN npm run build


# -------- Build Backend --------
FROM golang:1.22 AS backend-builder

WORKDIR /app
COPY backend/go.mod backend/go.sum ./
RUN go mod download
COPY backend .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server


# -------- Final Image --------
FROM debian:stable-slim

WORKDIR /app

# copiar binário Go
COPY --from=backend-builder /app/server .

# copiar frontend buildado
COPY --from=frontend-builder /app/frontend/dist ./dist

EXPOSE 8080

CMD ["./server"]
